[SUPER:MSSQL]
[MULTILINE_START]
delete from super.dbo.TIDSSTYRING where PARAMETERE like '%Kontering.exe -KONTERING' ; 
INSERT INTO SUPER.dbo.TIDSSTYRING(TIDSSTYRINGID ,UTFOERTID ,NESTEGANG ,KOMMANDO ,NODENR ,PARAMETERE ,VENT ,FLGAKTIV ,JOBBTYPE) VALUES((SELECT MAX(TIDSSTYRINGID)+1 FROM SUPER..TIDSSTYRING) , '00:45:00', getdate() , 3 ,1 ,'C:\Super\Kontering.exe -KONTERING' , 'T'  , 'T' , 1);
[MULTILINE_END]